# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all unit tests"
  lane :test do
    scan(
      scheme: "Household Management",  # Replace with your Xcode scheme name
      device: "iPhone 16 Pro (18.2)",
      clean: true,                # Clean the build folder before testing
      code_coverage: true,         # Optional: Enable code coverage
      output_directory: "fastlane/test_results",
      output_types: "html",
      disable_concurrent_testing: true,  # Ensure tests run serially
      testplan: "Household Management"
    )
  end

  desc "Generate the coverage reports using slather"
  lane :generate_coverage_report do
    slather(
      proj: "Household Management.xcodeproj",
      scheme: "Household Management",
      html: true,
      output_directory: "fastlane/test_results/coverage"
    )
  end
end
