name: Run Tests

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Tests
        run: fastlane test

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-report
          path: fastlane/test_results/report.html
    
      - name: Generate Coverage Report
        if: always()
        run: fastlane generate_coverage_report

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: fastlane/test_results/coverage

